/**
 * Read-only shared ingredient catalog. Ids are deterministic (uuid v5 of the
 * name) so the data migration is reproducible. gramsPerMl is an explicit
 * density that enables volume<->mass conversions for that ingredient only.
 */
export const CATEGORIES = [
	'Produce',
	'Meat & fish',
	'Dairy & eggs',
	'Bakery',
	'Pantry',
	'Spices',
	'Frozen',
	'Beverages',
	'Household',
	'Other'
];

// [name, category, gramsPerMl?, aliases[]]
export const CATALOG = [
	['onion', 'Produce', null, ['yellow onion', 'brown onion']],
	['red onion', 'Produce', null, []],
	['green onion', 'Produce', null, ['scallion', 'spring onion', 'scallions']],
	['garlic', 'Produce', null, []],
	['ginger', 'Produce', null, ['fresh ginger']],
	['carrot', 'Produce', null, ['carrots']],
	['celery', 'Produce', null, []],
	['potato', 'Produce', null, ['potatoes']],
	['sweet potato', 'Produce', null, ['sweet potatoes']],
	['tomato', 'Produce', null, ['tomatoes']],
	['cherry tomato', 'Produce', null, ['cherry tomatoes']],
	['bell pepper', 'Produce', null, ['capsicum', 'sweet pepper']],
	['chili pepper', 'Produce', null, ['chilli', 'chili', 'fresh chili']],
	['cucumber', 'Produce', null, []],
	['zucchini', 'Produce', null, ['courgette']],
	['eggplant', 'Produce', null, ['aubergine']],
	['broccoli', 'Produce', null, []],
	['cauliflower', 'Produce', null, []],
	['cabbage', 'Produce', null, []],
	['kale', 'Produce', null, []],
	['spinach', 'Produce', null, ['baby spinach']],
	['lettuce', 'Produce', null, []],
	['mushroom', 'Produce', null, ['mushrooms', 'button mushrooms']],
	['lemon', 'Produce', null, ['lemons']],
	['lime', 'Produce', null, ['limes']],
	['orange', 'Produce', null, ['oranges']],
	['apple', 'Produce', null, ['apples']],
	['banana', 'Produce', null, ['bananas']],
	['avocado', 'Produce', null, ['avocados']],
	['parsley', 'Produce', null, ['flat-leaf parsley']],
	['cilantro', 'Produce', null, ['coriander leaves', 'fresh coriander']],
	['basil', 'Produce', null, ['fresh basil']],
	['mint', 'Produce', null, ['fresh mint']],
	['rosemary', 'Produce', null, []],
	['thyme', 'Produce', null, []],
	['dill', 'Produce', null, []],
	['chicken breast', 'Meat & fish', null, ['chicken breasts']],
	['chicken thigh', 'Meat & fish', null, ['chicken thighs']],
	['whole chicken', 'Meat & fish', null, []],
	['ground beef', 'Meat & fish', null, ['minced beef', 'beef mince']],
	['beef steak', 'Meat & fish', null, ['steak']],
	['pork chop', 'Meat & fish', null, ['pork chops']],
	['ground pork', 'Meat & fish', null, ['pork mince']],
	['bacon', 'Meat & fish', null, []],
	['sausage', 'Meat & fish', null, ['sausages']],
	['salmon', 'Meat & fish', null, ['salmon fillet']],
	['white fish', 'Meat & fish', null, ['cod', 'haddock']],
	['shrimp', 'Meat & fish', null, ['prawns', 'prawn']],
	['tuna', 'Meat & fish', null, ['canned tuna']],
	['egg', 'Dairy & eggs', null, ['eggs']],
	['milk', 'Dairy & eggs', '1.03', ['whole milk']],
	['butter', 'Dairy & eggs', '0.911', ['unsalted butter']],
	['cream', 'Dairy & eggs', '1.0', ['heavy cream', 'double cream', 'whipping cream']],
	['sour cream', 'Dairy & eggs', '1.0', []],
	['yogurt', 'Dairy & eggs', '1.03', ['yoghurt', 'greek yogurt']],
	['cheddar', 'Dairy & eggs', null, ['cheddar cheese']],
	['parmesan', 'Dairy & eggs', null, ['parmigiano', 'parmesan cheese']],
	['mozzarella', 'Dairy & eggs', null, []],
	['feta', 'Dairy & eggs', null, ['feta cheese']],
	['cream cheese', 'Dairy & eggs', null, []],
	['bread', 'Bakery', null, ['loaf']],
	['tortilla', 'Bakery', null, ['tortillas']],
	['pita', 'Bakery', null, ['pita bread']],
	['all-purpose flour', 'Pantry', '0.53', ['flour', 'plain flour']],
	['bread flour', 'Pantry', '0.55', ['strong flour']],
	['whole wheat flour', 'Pantry', '0.51', ['wholemeal flour']],
	['sugar', 'Pantry', '0.85', ['white sugar', 'granulated sugar', 'caster sugar']],
	['brown sugar', 'Pantry', '0.82', []],
	['powdered sugar', 'Pantry', '0.51', ['icing sugar', 'confectioners sugar']],
	['honey', 'Pantry', '1.42', []],
	['maple syrup', 'Pantry', '1.32', []],
	['baking powder', 'Pantry', '0.9', []],
	['baking soda', 'Pantry', '0.9', ['bicarbonate of soda']],
	['instant yeast', 'Pantry', null, ['yeast', 'dry yeast', 'active dry yeast']],
	['cornstarch', 'Pantry', '0.54', ['cornflour']],
	['rolled oats', 'Pantry', '0.4', ['oats', 'porridge oats']],
	['rice', 'Pantry', '0.85', ['white rice', 'long grain rice']],
	['basmati rice', 'Pantry', '0.85', []],
	['arborio rice', 'Pantry', '0.85', ['risotto rice']],
	['pasta', 'Pantry', null, ['spaghetti', 'penne', 'rigatoni']],
	['couscous', 'Pantry', '0.75', []],
	['quinoa', 'Pantry', '0.75', []],
	['red lentils', 'Pantry', '0.85', ['lentils']],
	['chickpeas', 'Pantry', null, ['garbanzo beans', 'canned chickpeas']],
	['black beans', 'Pantry', null, []],
	['kidney beans', 'Pantry', null, []],
	['canned tomatoes', 'Pantry', null, ['crushed tomatoes', 'tinned tomatoes', 'diced tomatoes']],
	['tomato paste', 'Pantry', '1.1', ['tomato puree']],
	['coconut milk', 'Pantry', '1.0', ['full-fat coconut milk']],
	['chicken stock', 'Pantry', '1.0', ['chicken broth']],
	['vegetable stock', 'Pantry', '1.0', ['vegetable broth']],
	['olive oil', 'Pantry', '0.92', ['extra virgin olive oil']],
	['vegetable oil', 'Pantry', '0.92', ['canola oil', 'sunflower oil', 'neutral oil']],
	['sesame oil', 'Pantry', '0.92', []],
	['soy sauce', 'Pantry', '1.1', []],
	['fish sauce', 'Pantry', '1.1', []],
	['white miso', 'Pantry', '1.1', ['miso', 'miso paste']],
	['vinegar', 'Pantry', '1.0', ['white vinegar']],
	['apple cider vinegar', 'Pantry', '1.0', []],
	['balsamic vinegar', 'Pantry', '1.05', []],
	['mustard', 'Pantry', '1.0', ['dijon mustard']],
	['mayonnaise', 'Pantry', '0.91', ['mayo']],
	['peanut butter', 'Pantry', '1.1', []],
	['olives', 'Pantry', null, ['green olives', 'black olives']],
	['capers', 'Pantry', null, []],
	['walnuts', 'Pantry', null, []],
	['almonds', 'Pantry', null, []],
	['peanuts', 'Pantry', null, []],
	['sesame seeds', 'Pantry', '0.6', []],
	['chocolate', 'Pantry', null, ['dark chocolate', 'chocolate chips']],
	['cocoa powder', 'Pantry', '0.5', []],
	['vanilla extract', 'Pantry', '0.88', ['vanilla']],
	['salt', 'Spices', '1.2', ['fine sea salt', 'table salt', 'kosher salt']],
	['flaky salt', 'Spices', null, ['flaky sea salt', 'sea salt flakes']],
	['black pepper', 'Spices', null, ['pepper', 'ground black pepper']],
	['paprika', 'Spices', null, ['smoked paprika']],
	['cumin', 'Spices', null, ['ground cumin', 'cumin seeds']],
	['coriander', 'Spices', null, ['ground coriander']],
	['turmeric', 'Spices', null, []],
	['curry powder', 'Spices', null, []],
	['garam masala', 'Spices', null, []],
	['chili flakes', 'Spices', null, ['red pepper flakes', 'chilli flakes']],
	['chili powder', 'Spices', null, []],
	['cinnamon', 'Spices', null, ['ground cinnamon']],
	['nutmeg', 'Spices', null, []],
	['oregano', 'Spices', null, ['dried oregano']],
	['dried thyme', 'Spices', null, []],
	['bay leaf', 'Spices', null, ['bay leaves']],
	['cayenne', 'Spices', null, ['cayenne pepper']],
	['frozen peas', 'Frozen', null, ['peas']],
	['frozen spinach', 'Frozen', null, []],
	['frozen berries', 'Frozen', null, ['mixed berries']],
	['ice cream', 'Frozen', null, []],
	['water', 'Beverages', '1.0', []],
	['coffee', 'Beverages', null, ['ground coffee', 'coffee beans']],
	['tea', 'Beverages', null, ['tea bags']],
	['orange juice', 'Beverages', '1.04', []],
	['white wine', 'Beverages', '0.99', []],
	['red wine', 'Beverages', '0.99', []],
	['beer', 'Beverages', '1.01', []],
	['paper towels', 'Household', null, ['kitchen roll']],
	['dish soap', 'Household', null, ['washing up liquid']],
	['aluminium foil', 'Household', null, ['aluminum foil', 'foil']],
	['baking paper', 'Household', null, ['parchment paper']]
];
